sudo: false
language: go
matrix:
  include:
  - go: "1.13.x"
  - go: "1.14.x"
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=tracing.coverprofile
  - goveralls -coverprofile=tracing.coverprofile -service=travis-ci
